version: "3"

services:
  db:
    image: postgres:12
    container_name: qchat
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=qchat
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - ./sql/*:/sql